### ISSUE TITLE
在我未定义的区域写flash

### ISSUE THREAD

**Issue by dongbowen-dbw** [armink/EasyFlash#101]
我使用的是泰凌8258蓝牙芯片，代码里EF_START_ADDR定义的是0x78000，在ef_port_write函数内我打印了写入的起始地址，发现每次初始化的时候会在地址0x10235写入数据，这是什么原因
![0x10235](https://user-images.githubusercontent.com/54016831/81795393-a65f5d00-953e-11ea-9695-05bf0095b07e.jpg)

**Comment by armink** [comment]
不太清楚，建议单步调试跟一下

**Comment by armink** [comment]
是否还有更新？如果没更新 issue 先关闭了

**Comment by dongbowen-dbw** [comment]
可能是sdk的问题，换了个sdk移植成功了。




| |
董博文
邮箱：17855822907@163.com
|

签名由 网易邮箱大师 定制

在2020年05月17日 09:46，朱天龙 (Armink) 写道：

是否还有更新？如果没更新 issue 先关闭了
