### ISSUE TITLE
任务里使用env , 占用堆栈过大

### ISSUE THREAD

**Issue by luzefeng123** [armink/EasyFlash#102]
我开了一个任务, 在未读取env 的情况下, 使用线程栈 256 足够用, 但是加上ef_get_env(name) 后, 出现了硬件访问错误, 知道把此线程栈增加到1024 , 才正常运行, 查看栈使用 97% , 有知道这是什么情况的吗

**Comment by luzefeng123** [comment]
我使用的版本是v4.01 貌似发错位置了

**Comment by armink** [comment]
这个应该是正常情况的

**Comment by luzefeng123** [comment]
哦哦, 好的, 我把操作env 统一放在一个线程里, 这也不算问题了
