### ISSUE TITLE
另外请问有 关于 plugins/types/  的范例吗。

### ISSUE THREAD

**Issue by qinhao4832** [armink/EasyFlash#11]
另外请问有 关于 plugins/types/  的范例吗。
我使用起来，提示

0> [Flash]Memory full!
 0> [Flash]Memory full!

代码：
static void test_env(void) {
    uint32_t i_boot_times = NULL;
    char *c_old_boot_times, c_new_boot_times[11] = {0};
    char test_flash[20] = {"1234asdasdasd"} ;
		char test_flash1[20] = {"1234asdasdasd"} ;

	
		ef_get_char_array("test_flash",test_flash1);
		SEGGER_RTT_printf(0,"test_flash = %d \n\r", test_flash1[0]);

		for(u16 i = 0;i<20;i++)
		{
			   test_flash[i] = i;
		}
		EfErrCode ERR = ef_set_char_array("test_flash", test_flash, 20);
		ef_save_env();
		SEGGER_RTT_printf(0,"ERR = %d \n\r", ERR);

		ef_print_env();
}

log显示：
0> [SFUD](..\sfud\src\sfud_sfdp.c:311) Flash device supports 64KB block erase. Command is 0xD8.
 0> [SFUD]Find a GigaDevice flash chip. Size is 2097152 bytes.
 0> [SFUD](..\sfud\src\sfud.c:727) Flash device reset success.
 0> [SFUD]SST25VF016B flash device is initialize success.
 0> [Flash](..\easyflash\src\ef_env.c:144) ENV start address is 0x00000000, size is 4096 bytes.
 0> [Flash](..\easyflash\src\ef_env.c:760) Calculate ENV CRC32 number is 0xFCEEFD14.
 0> [Flash](..\easyflash\src\ef_env.c:772) Verify ENV CRC32 result is OK.
 0> [Flash](..\easyflash\src\easyflash.c:96) EasyFlash V3.0.0 is initialize success.
 0> [Flash](..\easyflash\src\easyflash.c:100) You can get the latest version on https://github.com/armink/EasyFlash .
 0> [Flash]Couldn't find this ENV(test_flash)!
 0> test_flash = 49 
 0> [Flash]Memory full!
 0> [Flash]Memory full!
 0> ERR = 5 
 0> iap_need_copy_app=0
 0> iap_copy_app_size=0
 0> stop_in_bootloader=0
 0> device_id=1
 0> boot_times=24
 0> 
 0> ENV size: 100/2048 bytes.

**Comment by armink** [comment]
- 如果看了 EasyFlash 常规 API 的文档，那么 types 还是比较容易理解的，这里有 types 插件介绍 https://github.com/armink/EasyFlash/tree/master/easyflash/plugins/types。
- Memory full! 是因为你的动态内存不足。请确认单片机有足够的堆空间，并已开启动态内存管理功能。
