### ISSUE TITLE
能否支持二进制类型的key？

### ISSUE THREAD

**Issue by CkovMk** [armink/EasyFlash#112]
如题，我在应用中需要将二进制键-值对存入Flash保存，目前采用的方案是将二进制值序列化成字符串，再用EF保存。这种方式较为不便，时间开销较大，而且不容易实现类似模糊查询的功能。请问有没有方法可以支持二进制类型的键值？
另，如果我的二进制键值是一个结构体，能否根据结构体中的某个成员变量值进行模糊搜索？
> 我觉得如果有一个能够方便地遍历所有K-V对的迭代器，就可以十分方便地实现这种功能。
十分感谢。

**Comment by armink** [comment]
二进制的键值是支持的，二进制的键名目前还不支持
