### ISSUE TITLE
请问这样的应用，EasyFlash适合吗

### ISSUE THREAD

**Issue by qinhao4832** [armink/EasyFlash#12]
请问easyflash，适合用于这样的场合吗：

  从串口接入256 Byte/包 的数据，然后存到SPI flash中。

  数据是图片数据，会有很多包数据，连续传输。

 后续会从SPI flash 取出数据，刷到TFT LCD上。

请问EasyFlash 用哪个API函数，适合这样的应用

**Comment by armink** [comment]
单纯的只是 256B 数据，接收缓冲区类型设为 char*，只是用 ef_set_env 就足够了。

感觉你对 EasyFlash 并不了解，务必先仔细看下说明文档，会使用 Demo 再上手开发。
