### ISSUE TITLE
Null pointer dereference issue

### ISSUE THREAD

**Issue by firmianay** [armink/EasyFlash#129]
hi, there seems to be a Null pointer dereference issue in the `find_env` function of the `ef-env.c` when `EF_ENV_USING_CACHE` is enable:

```c
del_env(NULL, env, false);

if (find_env(key, &env)) {

size_t key_len = strlen(key);
```

**Comment by armink** [comment]
你好，方便提交 PR 吗

**Comment by firmianay** [comment]
我本身对easyflash不熟悉，只是发现了这个问题，还是作者改一下吧
