### ISSUE TITLE
像下面这种语句会被优化掉吧？

### ISSUE THREAD

**Issue by geniusgogo** [armink/EasyFlash#13]
/* calculate the sector header address */
    header_addr = addr / EF_ERASE_MIN_SIZE * EF_ERASE_MIN_SIZE;

应该改成header = addr & (EF_ERASE_MIN_SIZE - 1);

**Comment by ShareCat** [comment]
header = addr & (~(EF_ERASE_MIN_SIZE - 1));

**Comment by armink** [comment]
@ShareCat 欢迎贡献 pull request 哈

**Comment by armink** [comment]
已修正~~多谢反馈
