### ISSUE TITLE
log_index2addr 函数存在隐藏风险，建议优化

### ISSUE THREAD

**Issue by i-jaffer** [armink/EasyFlash#146]
`ef_log.c` 文件内的 `log_index2addr` 函数使用存在隐藏风险，建议可以优化

当给 `log_index2addr` 传入的参数`index` 的值 大于 2倍`LOG_AREA_SIZE`时，回导致计算出来的flash物理地址错误

建议将返回值计算
 `return log_start_addr + index + header_total_offset - LOG_AREA_SIZE;` 
修改为
`return (log_start_addr + index + header_total_offse)t % LOG_AREA_SIZE;`

尽管此函数仅由`ef_log_read`调用，且`ef_log_read`函数内做了`EF_ASSERT(index < cur_using_size);`判断，目前整体是安全的，但是此函数是不安全的，为防止后续其他函数调用是引入风险，建议修改

**Comment by armink** [comment]
欢迎提交修改的 PR 呢

**Comment by i-jaffer** [comment]
> 

PR已提交
