### ISSUE TITLE
有2个关于存储的问题

### ISSUE THREAD

**Issue by ShareCat** [armink/EasyFlash#16]
目前环境变量都是键值对的方式存储，存储都是字符串形式

1、如果要存储一个结构体，怎么办？只能将结构体每个成员分别存储？这样貌似太麻烦..
2、如果要存储的是一个数组，怎么办？因为这个数组有可能中间某个元素为0x00，0x00是字符串结束符号，直接存储肯定不行，存储时候会将0x00后面的元素都丢掉了。我的想法是只能将每个元素都分别拆开，比如0x00拆分成0和0，再转化成字符串成了0x30和0x30进行存储。不知道是否有更好的办法？

**Comment by armink** [comment]
你需要的是 EasyFlash 的类型转换插件：
https://github.com/armink/EasyFlash/tree/master/easyflash/plugins/types

**Comment by HubertXie** [comment]
是否可以使用base64编码进行转换存储，或者使用类似的编解码方式将数据转换为字符串。
感觉struct2json的使用还是很麻烦，而且消耗内存也比较大。

**Comment by armink** [comment]
当然可以，我们有产品也是这样做的，只是 json 的可读性比较强。
