### ISSUE TITLE
移植到spi flash使用中遇到问题

### ISSUE THREAD

**Issue by chenxiuqimr** [armink/EasyFlash#21]
移植到spi flash 用了一段时间发现，如果flash是旧的本身有存过其他数据时，在使用easyflash会出现异常，
会进入到这一步，ef_port_erase ---> EF_ASSERT(addr % EF_ERASE_MIN_SIZE == 0); 这里卡住
    
仿真发现ef_load_env里ef_port_read(get_env_start_addr(), &area0_cur_using_addr, 4);得到的area0_cur_using_addr值会有问题，导致上面的卡住情况

是不是使用easyflash前必须要对flash做一次整片擦除呢？

**Comment by armink** [comment]
是的，否则脏数据可能会有干扰。可以加入个 magic word ，初始时检测，不正确自动恢复默认。
