### ISSUE TITLE
存储空字符串问题

### ISSUE THREAD

**Issue by outely** [armink/EasyFlash#22]
使用`EfErrCode ef_set_env(const char *key, const char *value)`存储空value时是删除对应的Map。
但又可以通过`ef_env_set_default()`将默认环境变量列表中的值为空的Map存入flash。如
`static const ef_env default_env_set[] = {
		{"password",""}
};`
因为在某些应用场景下可能会存储有意义的空串值，如空密码。
是否能够通过加入一个删除Map的API 取代`ef_set_env()`中value为空时删除Map的功能。

**Comment by armink** [comment]
类似 `ef_del_env("key")` ？

**Comment by outely** [comment]
是的。增加`ef_del_env("key")`实现删除Map功能，让`ef_set_env("key", "")`能够正常保存空串。

**Comment by armink** [comment]
好的，你方便改下代码，发起下 pull request 吗？

**Comment by outely** [comment]
OK 稍等

**Comment by armink** [comment]
fixed in #24
