### ISSUE TITLE
ef_types中的问题

### ISSUE THREAD

**Issue by XXXXzzzz000** [armink/EasyFlash#29]
在ef_types.c中
```
double ef_get_double(const char *key) {
    char *value = ef_get_env(key);
    if(value) {
        return atof(value);
    } else {
        EF_INFO("Couldn't find this ENV(%s)!\n", key);
        return NULL;
    }
}
```
此处返回了NULL,是否将其更改为
int ef_get_double(const char *key,double * out_value)
返回值指示是否成功,参数输出,会更好呢?
因为我在移植的过程中此处发生了报错.

**Comment by armink** [comment]
应该返回 0.0f 才是

**Comment by XXXXzzzz000** [comment]
这样的话好像就没办法分辨是错误还是存储的值了吧。 119524428 邮箱119524428@qq.com 签名由 网易邮箱大师 定制 在2018年09月13日 19:02，朱天龙 (Armink) 写道： 应该返回 0.0f 才是 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by XXXXzzzz000** [comment]
这样的话好像就没办法分辨是错误还是存储的值了吧.

**Comment by armink** [comment]
有日志的

**Comment by armink** [comment]
同时也建议，执行前使用 ef_get_env("key") 来检查下是否存在

**Comment by XXXXzzzz000** [comment]
好的,谢谢啦
