### ISSUE TITLE
移植说明 port.md

### ISSUE THREAD

**Issue by JGINGIT** [armink/EasyFlash#3]
> 5.1.1 磨损平衡/常规 模式

> 磨损平衡：由于flash在写操作之前需要擦除且使用寿命有限，所以需要设计合理的磨损平衡（写平衡）机制，来保证数据被安全的保存在未到擦写寿命的Flash区中。

> 默认状态：常规模式
> 常规模式：关闭 ```FLASH_ENV_USING_WL_MODE```
> 磨损平衡模式：打开```EF_ENV_USING_WL_MODE```

上面的“常规模式”应该是关闭```EF_ENV_USING_WL_MODE``` 而不是 ```FLASH_ENV_USING_WL_MODE```

**Comment by armink** [comment]
确实是写错了，多谢反馈哈~
