### ISSUE TITLE
最新的版本开启  #define EF_ENV_USING_WL_MODE和 #define EF_ENV_AUTO_UPDATE 编译出错

### ISSUE THREAD

**Issue by chenxiuqimr** [armink/EasyFlash#31]
提示错误
.\build\app.axf: Error: L6218E: Undefined symbol get_env_system_addr (referred from ef_env_wl.o).
看来下代码感觉是 “修复EF_ENV_AUTO_UPDATE后每次重启都会自动更新” 引起的bug 
麻烦大佬们检查下看看

**Comment by chenxiuqimr** [comment]
static EfErrCode env_auto_update(void)里调用到get_env_system_addr()

ef_port_read(get_env_system_addr() + ENV_PARAM_INDEX_VER_NUM * 4,
               &env_cache[ENV_PARAM_INDEX_VER_NUM] , 4);

实际上ef_env_wl.c里不存在该函数

**Comment by armink** [comment]
多谢你的反馈哈。确实存在这个错误，刚刚已经修复了，你再试试吧。

**Comment by armink** [comment]
没问题先关闭了，有问题再打开
