### ISSUE TITLE
请问ef_log 写满了会如何

### ISSUE THREAD

**Issue by qinhao4832** [armink/EasyFlash#33]
我的log区，配置了80K
#define LOG_AREA_SIZE             (20 * EF_ERASE_MIN_SIZE)     /* 80K */

然后，如下的代码，测试 写满 log
		while(1)
		{
		
				ret  = ef_log_write((const uint32_t *)logTest, 76) ; //每次写76字
			
				EF_INFO("ef_log_get_used_size[%ld]\n\r",ef_log_get_used_size());
		}
 运行意思写log后，ef_log_get_used_size的尺寸从0~80K，然后一直在 70+K ~80+K 之间循环。以下是截取一段打印输出：
Flash]ef_log_get_used_size[79420]
[Flash]ef_log_get_used_size[79496]
[Flash]ef_log_get_used_size[79572]
[Flash]ef_log_get_used_size[79648]
[Flash]ef_log_get_used_size[79724]
[Flash]ef_log_get_used_size[79800]
[Flash]ef_log_get_used_size[79876]
[Flash]ef_log_get_used_size[79952]
[Flash]ef_log_get_used_size[80028]
[Flash]ef_log_get_used_size[80104]
[Flash]ef_log_get_used_size[80180]
[Flash]ef_log_get_used_size[80256]
[Flash]ef_log_get_used_size[80332]
[Flash]ef_log_get_used_size[80408]
[Flash]ef_log_get_used_size[80484]
[Flash]ef_log_get_used_size[80560]
[Flash]ef_log_get_used_size[80636]
[Flash]ef_log_get_used_size[80712]
[Flash]ef_log_get_used_size[80788]
[Flash]ef_log_get_used_size[80864]
[Flash]ef_log_get_used_size[80940]
[Flash]ef_log_get_used_size[81016]
[Flash]ef_log_get_used_size[81092]
[Flash]ef_log_get_used_size[81168]
[Flash]ef_log_get_used_size[81244]
[Flash]ef_log_get_used_size[81320]
[Flash]ef_log_get_used_size[81396]
[Flash]ef_log_get_used_size[81472]
[Flash]ef_log_get_used_size[81548]
[Flash]ef_log_get_used_size[81624]
[Flash]ef_log_get_used_size[81700]
[Flash]ef_log_get_used_size[81776]
[Flash]ef_log_get_used_size[77760]
[Flash]ef_log_get_used_size[77836]
[Flash]ef_log_get_used_size[77912]
[Flash]ef_log_get_used_size[77988]
[Flash]ef_log_get_used_size[78064]

请问ef_log_get_used_size() 的尺寸一直在70~80K之间循环的情况，正常吗？

**Comment by armink** [comment]
正常的，满了以后会清空最早存储的那个扇区。
