### ISSUE TITLE
EasyFlash对数据的存储是否只支持字符串形式的？

### ISSUE THREAD

**Issue by 442534820** [armink/EasyFlash#35]
看write_env的接口，value是const char*类型的，EF是否不支持二进制存取？

**Comment by armink** [comment]
暂不支持嗯，后面会去支持。现在可以用 base64 转一下去存

**Comment by 442534820** [comment]
> 
> 
> 暂不支持嗯，后面会去支持。现在可以用 base64 转一下去存

感谢回复，效率好高啊

**Comment by armink** [comment]
EasyFlash 新推出了 4.0, 版本，支持非字符串模式，你可以再试试哈

**Comment by armink** [comment]
最新正式版已经支持各种类型了，可以试试
