### ISSUE TITLE
EF_WRITE_GRAN = 1的时候，F1 SPI FLASH demo 出错

### ISSUE THREAD

**Issue by qinhao4832** [armink/EasyFlash#40]
[Flash](..\Src\easyflash\src\ef_env.c:850) env_len 1569 EF_WG_ALIGN(key_len) 13 key_len 13  EF_WG_ALIGN(buf_len) 1536    //此处是我自己加的打印。 key_len 

[Flash](..\Src\easyflash\port\ef_port.c:129) (size % 4 == 0) has assert failed at ef_port_write.

**Comment by armink** [comment]
这个断言判断是有些多余了，你方便给删掉，提个 pr 上来吗？
