### ISSUE TITLE
比较：EasyFlash 和 littleFs

### ISSUE THREAD

**Issue by Linjieqiang** [armink/EasyFlash#41]
最近一项目中，在纠结使用littleFs还是EasyFlash，大神能否分析下各自的优缺点？

**Comment by armink** [comment]
littlfs 是文件系统，EasyFlash 是 KV 存储、日志存储，两者没有可比性吧

**Comment by Linjieqiang** [comment]
好的 谢谢大神 我先用这套easyflash试试 哈
