### ISSUE TITLE
EasyFlash / demo / iap / ymodem+rtt.c 中的iap_get_app_addr()没有发现函数原型

### ISSUE THREAD

**Issue by lee88688** [armink/EasyFlash#5]
如题，我基本找完了代码，但是没有发现函数原型。想知道应该如何设置app的入口地址

**Comment by armink** [comment]
`iap_get_app_addr()`是获取App入口地址的方法，这个不是EasyFlash做的事情，应该由App来提供。你就宏定义下这个地址，然后通过全局的iap_get_app_addr()方法获取回来就行。

**Comment by lee88688** [comment]
app的编译与不同没有iap的编译相同吗？

**Comment by armink** [comment]
你说的`编译`具体指的什么内容？

**Comment by lee88688** [comment]
app和bootloader是分别编译下载到单片机中的，编译就是生成最终的二进制可执行文件。我对iap了解不是很深，希望能讲解一下app以及bootloader两个在编译的时候有什么区别吗？

**Comment by armink** [comment]
链接文件会不一样。细节方面建议你仔细查阅相关资料。
