### ISSUE TITLE
关于特征字env的字长选择

### ISSUE THREAD

**Issue by ZanoZ** [armink/EasyFlash#50]
作者(armink)你好：
看了下env的好多标志，比如存储状态，脏状态，都是32位的，
为什么要放这么多字节呢？记录的状态只有3，4个这样的
要知道eeprom的读写字节数越多，速度越慢呀。
还请教这里是否有什么原因呢。
谢谢~

**Comment by armink** [comment]
这个取决于你的 Flash 写粒度的，如果只有 1个 bit ，占用的空间最小

https://github.com/armink/EasyFlash/blob/03095fb2e301ccabb8c3ab0fa4864f9247cfa936/easyflash/src/ef_env.c#L86-L94

**Comment by ZanoZ** [comment]
啊，原来如此，谢谢啦
