### ISSUE TITLE
关于EasyFlash的存储性能指标

### ISSUE THREAD

**Issue by ZanoZ** [armink/EasyFlash#52]
你好，关于EasyFlash的系统性能，比如有效存储空间:总存储空间大小，最多支持变量个数等等，是否有示例数据评估？
我建议这方面进行一些说明，有助于大家使用的时候知道正在使用的东西，极限在哪里，也能有助于安全可靠地使用它。
不管怎样，谢谢作者的共享和公开。
看来作者也在魔都，有机会可以一起交流啊。

**Comment by armink** [comment]
评估的话可以直接使用 EasyFlash 里自带的 demo 工程，你可以先试试。

还可以加我 QQ ，线下交流也是可以的。
