### ISSUE TITLE
STM32 Flash擦写操作导致USART接收丢数据

### ISSUE THREAD

**Issue by redocCheng** [armink/EasyFlash#53]
基本情况：
平台：stm32f103vct6 裸机
串口接收方式：DMA接收中断
FLASH擦除时间：Page/Mass Erase time: 20 ms  （文档号-**AN2594 Application note**）
FLASH擦除期间的描述：写/擦除操作进行期间不能从 Flash 中执行代码，这句话一般地方没有，取自**STM32F7x参考手册**

问题简要描述：
根据上述，stm32 FLASH擦除时无法响应中断，若此时有数据进来，会直接导致丢包。自己测试每次丢数据flash刚好擦除了一次。

目前的解决方式：
1、采用外部FLASH，
2、控制下发时间间隔，

请问还有么有更好的方式？

**Comment by armink** [comment]
使用 DMA 接收就行了，记得 rx buffer 不要太小
