### ISSUE TITLE
移植Easyflash 中update更新固件方法

### ISSUE THREAD

**Issue by zengwangfa** [armink/EasyFlash#54]
- 平台STM32F407ZGT6
- 情况描述
    - 之前移植好是可以用update串口更新程序方法
    - 后面可能工程中加了一些文件，到时使用update方法时出现图片中无法更新的情况。
    - 请问这样一般是什么导致的？

![image](https://user-images.githubusercontent.com/40621296/56558947-d3a73900-65d2-11e9-8701-2167a0fba06d.png)

**Comment by armink** [comment]
参考下 这个软件包 吧 https://github.com/RT-Thread-packages/ota_downloader

**Comment by zengwangfa** [comment]
嗯，解决了。
- 原来是我在定时器中有串口的操作导致无法进行Ymode通信
![image](https://user-images.githubusercontent.com/40621296/56591454-5653e680-661b-11e9-8212-00bf432384db.png)

**Comment by armink** [comment]
Ymodem 时可以禁止日志的输出

**Comment by zengwangfa** [comment]
> Ymodem 时可以禁止日志的输出

嗯是的，谢谢龙哥一直的指导。

**Comment by zengwangfa** [comment]
我显示Dowen firmware to falsh ok
但是好像程序并没有更新。
