### ISSUE TITLE
read_env 问题

### ISSUE THREAD

**Issue by xwiron** [armink/EasyFlash#56]
`static EfErrCode read_env(env_meta_data_t env)
{
    ...
  crc_data_len = env->len - ENV_NAME_LEN_OFFSET;
    ...
}`

读取数据错误时，crc_data_len 出现数据长度超长

**Comment by armink** [comment]
欢迎提交 pr 哈

**Comment by armink** [comment]
多谢反馈，问题已修正，欢迎尝试最新代码。
