### ISSUE TITLE
如何删除某个环境变量，以及保存自定义类型数据到Flash。

### ISSUE THREAD

**Issue by heisewangluo** [armink/EasyFlash#6]
刚体验了EasyFlash和EasyLogger，感觉还是挺方便的。
在此有些疑问和建议：

1. **环境变量**不能删除。
2. 既然是存储库，却不能存储自定义类型的数据到Flash。
3. Falsh和Logger库，为什么不合并呢？
4. 可以的话，把版本号打个标签。

**Comment by armink** [comment]
- 1、环境变量支持删除， `setenv` 的时候将 `value` 设置为空即可，API 文档中有说明；
- 2、可以使用 EasyFlash 提供的 types 插件功能，已支持更多类型，包括数组或结构体；
- 3、EasyFlash 侧重点是 Flash 的数据管理，而 EasyLogger 侧重点是 日志处理 ，两者功能完全不一样。同时，在层级上 EasyLogger 也要高于 EasyFlash ；
- 4、目前的版本号管理使用的是提交日期的形式，如果源代码改动都会更新版本号，所以并不太适合 Git 标签的方式。

**Comment by heisewangluo** [comment]
明白，谢谢你抽空阅读和解答！
