### ISSUE TITLE
When will be V4.0 released ?

### ISSUE THREAD

**Issue by ShareCat** [armink/EasyFlash#62]
When will be V4.0 released ?
We are looking forward to it, TKS !

**Comment by armink** [comment]
I am optimizing the query efficiency of env now. Other features are stable. It will be released as early as the end of June.

**Comment by ZanoZ** [comment]
所以4.0现在还没出来是吧.

**Comment by armink** [comment]
> 所以4.0现在还没出来是吧.

稍安勿躁，正式版还未发布

**Comment by ZanoZ** [comment]
哇,这么近,上班了?加个微信吧28277961

**Comment by ZanoZ** [comment]
https://github.com/ZanoZ/EEFile
我忍不住开始动手写了,不过我觉得还是有点浪费,大家造同一个轮子重复劳动啊....( ･᷄ὢ･᷅ )

**Comment by armink** [comment]
> https://github.com/ZanoZ/EEFile
> 我忍不住开始动手写了,不过我觉得还是有点浪费,大家造同一个轮子重复劳动啊....( ･᷄ὢ･᷅ )

你的链接打不开~~

跟大家同步下进展，上周末针对 env 及 sector 完成了缓存机制的开发，保证了安全性的前提下提升了效率，测试结果还不错，估计这周末能同步上来。

效率的问题解决后，其他剩余的小问题就很少了。

**Comment by hzm476172557** [comment]
you have done a great job, I think the easyflash 5 should do some subtraction. It will be better if you abandon the old APIs

**Comment by armink** [comment]
hi, all. 最近新版本新加入了缓存机制，查询，写入效率得到大幅提升，欢迎大家测试~~

目前，V4.0 基本没有待完善的功能了。等大家对缓存功能有更多的测试反馈后，近期就将正式发布。

**Comment by ZanoZ** [comment]
> > https://github.com/ZanoZ/EEFile
> > 我忍不住开始动手写了,不过我觉得还是有点浪费,大家造同一个轮子重复劳动啊....( ･᷄ὢ･᷅ )
> 
> 你的链接打不开~~
> 
> 跟大家同步下进展，上周末针对 env 及 sector 完成了缓存机制的开发，保证了安全性的前提下提升了效率，测试结果还不错，估计这周末能同步上来。
> 
> 效率的问题解决后，其他剩余的小问题就很少了。

写了一半,感觉太不成熟就先设成不公开了,我加你进去,还请指点哈.

**Comment by armink** [comment]
正式版已经发布了，欢迎使用
