### ISSUE TITLE
使用EasyFlash进行IAP更新程序，显示下载程序完成，但实际程序并没有更新

### ISSUE THREAD

**Issue by zengwangfa** [armink/EasyFlash#63]
![image](https://user-images.githubusercontent.com/40621296/59058142-91119580-88ce-11e9-9c61-964bf74aef10.png)
使用EasyFlash进行IAP更新程序，显示下载程序完成，但实际程序并没有更新，是什么问题呢？应该怎么解决？

**Comment by zengwangfa** [comment]
已经困扰了一周，还是没有找出问题。

**Comment by armink** [comment]
不太清楚，检查下写入地址吧

**Comment by zengwangfa** [comment]
好像只是将程序写入在了备份区，但是自动重启的时候并没有 【擦除用户程序】和【从备份拷贝应用程序】，这个应该如何解决呢？

测试很久了，之前移植是可以用的，困扰很久了，一般是什么原因呢？

**Comment by zengwangfa** [comment]
> 不太清楚，检查下写入地址吧

检查过了，地址应该是没有问题的。

**Comment by zengwangfa** [comment]
如何初始化 片内Flash作为设备呢？

**Comment by armink** [comment]
不明白你说的设备是指的什么。EasyFlash 对于 IAP 功能提供了一些 API  https://github.com/armink/EasyFlash/blob/master/docs/zh/api.md

功能很简单，你再看下 API 吧
