### ISSUE TITLE
关于gc机制

### ISSUE THREAD

**Issue by ylz0923** [armink/EasyFlash#67]
版本: 4.0.0的版本

情景:  easyflash的分区比较大1MB, 当空闲扇区剩下最后一个时触发gc后, 会擦出全部脏的区域耗时比较长1秒以上. 

建议: 有没有可能用懒擦除, 需要几个扇区就擦除几个.

**Comment by armink** [comment]
啥叫懒擦除？另外，GC 的阈值是可以设置的，详见 `EF_GC_EMPTY_SEC_THRESHOLD`

**Comment by ylz0923** [comment]
如果设置了EF_GC_EMPTY_SEC_THRESHOLD为>1 的数那么后面的最后(EF_GC_EMPTY_SEC_THRESHOLD-1)的扇区就永远用不到了吧

**Comment by ylz0923** [comment]
懒擦除, 就是用之前擦除, 现在的机制是先擦除好了待用. 这样保存env用的时间是不确定的

**Comment by armink** [comment]
可以试试最新代码，ENV 的写入速率得到很大的提升。

另外，对外的 GC  接口也将在 V4.1 被导出

**Comment by armink** [comment]
@ylz0923 今天优化了下代码，提升了下 GC 速度，你再试下最新代码吧

**Comment by TheSilencerPang** [comment]
您好！我在使用ef配合掉电检测来保存数据，但是当下次写入会触发gc时，擦除时间太久会导致保存失败。目前我的想法是在开机时，检测下次保存是否会触发gc来提前手动触发gc，以保证掉电保存的安全性。在v4.1中没有看到对外的gc，相关gc貌似都是static。我不希望修改源码。
