### ISSUE TITLE
关于缓存代码和前面的兼容问题

### ISSUE THREAD

**Issue by xuji520123** [armink/EasyFlash#68]
加了缓存的新代码和不带缓存的版本，两个版本间的env数据不能兼容

**Comment by armink** [comment]
是的，还好 4.0 没有发布

**Comment by armink** [comment]
加了缓存的新版本现在性能体验咋样？

**Comment by xuji520123** [comment]
hi armink，测试下来感觉现在主要瓶颈还是在块回收，特别是在 env move的时候会花费较长时间，各种env尺寸相差较大碎片相对容易出现时。回收目前是不是只要是脏块就会回收呢。

**Comment by armink** [comment]
现在是剩余空闲的分区不足（低于或等于设定阈值，目前是1）就会执行 GC 动作，执行 GC 时会遍历全部扇区，找到脏的扇区进行回收

**Comment by armink** [comment]
> hi armink，测试下来写入速度有较大提升，现在主要瓶颈是在块回收，特别是在 env move的时候会花费较长时间，各种env尺寸相差较大碎片相对容易出现时。回收目前是不是只要是脏块就会回收呢。

你好，欢迎尝试最新代码，对于 move_env 的速度提升还是挺明显的
