### ISSUE TITLE
V4.0.0版本移植到Apollo2出现hardfault

### ISSUE THREAD

**Issue by tianxiaoMCU** [armink/EasyFlash#70]
MCU：apollo2
SDK版本：V1.2.12
环境：keil V5.26.2

移植V4.0.0后出现hardfault，使用cmbacktrace定位，数据如下
![image](https://user-images.githubusercontent.com/40310665/63587720-43581f80-c5d7-11e9-92fd-92b39e298944.png)
addr2line定位结果：
![image](https://user-images.githubusercontent.com/40310665/63587871-a5188980-c5d7-11e9-945a-05b5007e1821.png)
根据定位结果找到
![image](https://user-images.githubusercontent.com/40310665/63587961-e741cb00-c5d7-11e9-9b8b-c2daa6e2ec50.png)
**但是这个函数没有被调用**

**单步调试，执行下图红框处后进入hardfault**
![image](https://user-images.githubusercontent.com/40310665/63588158-6800c700-c5d8-11e9-8d61-df8826a09b8e.png)

**Comment by armink** [comment]
cmb 显示的问题估计跟移植有关系，要确保 C 主栈等名称配置正确。

handfault 可以尝试看下单步的汇编指令情况，单独看你的截图没有看出有啥问题。

**Comment by tianxiaoMCU** [comment]
解决了，确实跟移植有关系。记错了EF_WRITE_GRAN的单位，拿来算word的数量导致的
