### ISSUE TITLE
关于env默认值的建议

### ISSUE THREAD

**Issue by zhouchuanfu** [armink/EasyFlash#79]
项目有可能不同的功能块都需要进行参数存储，而功能块又比较独立，为了功能块能够方便移植，那么能否将默认值的参数定义通过类似rtthread的初始化列表的方式，使用SECTION的方式来将默认参数分散到各自的功能块中去，删除一个功能块只需要删去对应的文件，而不用修改el_port.c文件。

**Comment by armink** [comment]
其实这个功能用户自身就这样实现，因为这个默认的 table 是可以支持动态传入的

如果环境变量比较少，其实我定义在一个文件中也挺方便的

**Comment by zhouchuanfu** [comment]
ok
