### ISSUE TITLE
均衡擦写问题

### ISSUE THREAD

**Issue by HubertXie** [armink/EasyFlash#8]
看了一下均衡擦写的实现，我的理解是通过擦除失败，或者写入失败时进行page的切换。
在STM32内部Flash上测试，发现实际不会进行page切换，一直对一个page进行擦写。

这样就达不到均衡擦写的目的了。

**Comment by armink** [comment]
你测试了多少次呢？我这边是有通过测试平台，进行过专业测试。

**Comment by ShareCat** [comment]
关于擦写平衡，我看了代码发现armink使用的方式是：先每次使用一个page擦写，当这个page使用一定次数后坏了，就会进行page切换，换到另外一个新的page擦写使用。

我一开始还以为是这次擦写是page1，那么下次就会使用page2，也就是page1和page2交换使用。（armink写的掉电保护用的是这个方式）

**Comment by HubertXie** [comment]
是的，内部实现我也看了。
感觉掉电保护其实就已经实现了擦写平衡。
增加一个配置选项就可以了，用于配置用多少个page来存储数据，这样就轮询在这几个page中写入数据就可以了。
